### PR TITLE
Add wsei token, add svg logo to SEI, fix USDC

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
Changes to pacific-1-evm assetlist
- Add WSEI
- Add svg logo to SEI
- Fix denom different from base in the USDC token

### CODE REVIEW

**Comment by tiagofilipenunes** [comment]
@SEImeme can you get the Master, Seitan and Burger contracts verified please?

**Comment by nullmames** [comment]
Hi @tiagofilipenunes i am traveling home to Australia at the moment. I will review after i get home. 
Looks good at the moment, but need to look intio the USDC a bit. The exponent is set to 0 at the monent which does not seem right and there are several versions. Looks like the one you have changed is an ibc denom from what i am assuming is noble. Can you advise why you have made the change?

**Comment by tiagofilipenunes** [comment]
> Hi @tiagofilipenunes i am traveling home to Australia at the moment. I will review after i get home. Looks good at the moment, but need to look intio the USDC a bit. The exponent is set to 0 at the monent which does not seem right and there are several versions. Looks like the one you have changed is an ibc denom from what i am assuming is noble. Can you advise why you have made the change?

Have a safe flight :) I took the USDC and USDT originally from the pacific-1 assetlist found here:
- USDT: https://github.com/Sei-Public-Goods/sei-assetlist/blob/e27113fd8cf8f2a694efa0d9b67dfb5c96fda394/assetlist.json#L542
- USDC: https://github.com/Sei-Public-Goods/sei-assetlist/blob/e27113fd8cf8f2a694efa0d9b67dfb5c96fda394/assetlist.json#L564

These tokens were linked with the token addresses added to pacific-1-evm assetlist as part of these proposals:
- USDT: https://www.seiscan.app/pacific-1/proposals/56
- USDC: https://www.seiscan.app/pacific-1/proposals/57

USDT denom matched base in the [PR](https://github.com/Sei-Public-Goods/sei-assetlist/pull/8) that added both assets, but USDC didn't. I believe the expected behaviour is for the first denom_units array element to have `exponent` = 0 and the `denom` to be the address of the network it is in - in this case, the EVM addresses. Let me know if you expect something else (perhaps adding the cosmos address to the list so we know they're linked) and I can keep it consistent, thanks :)

**Comment by SEImeme** [comment]
> @SEImeme can you get the Master, Seitan and Burger contracts verified please?

having trouble verifying. tried flattened code and didn't accept (neither remix or hardhat). 
also tried standard input json instead of flattened. - not accepeted
seiscan page only has a Twitter account as a contact but DMs are closed

any tips on how to make it work is welcome.

**Comment by tiagofilipenunes** [comment]
> > @SEImeme can you get the Master, Seitan and Burger contracts verified please?
> 
> having trouble verifying. tried flattened code and didn't accept (neither remix or hardhat). also tried standard input json instead of flattened. - not accepeted seiscan page only has a Twitter account as a contact but DMs are closed
> 
> any tips on how to make it work is welcome.

I know other people had problems with verifying with remix or hardhat. I would suggest to manually verify them using seitrace.

**Comment by tiagofilipenunes** [comment]
@nullmames this PR no longer affects the Master, Seitan and Burger tokens. Can you please review it as it is right now? Thank you!

**Comment by nullmames** [comment]
Okay. Lets merge this and can look at the others after verification.

**Pull request merged**
